### ISSUE TITLE
background colours from design into Data Tracker page

### ISSUE THREAD

**Issue by Jeena-Rajan** [ebi-ait/data-catalogue#51]
implement background colours from the design:
- grid background
- alternating row background

**Comment by amnonkhen** [comment]
For the MorPhiC demo of late Jan 2024, the styling was done in a hard coded way due to difficulties learning how to style ag-grid and angular material design. I will create a separate ticket for the purpose of a proper styling customisation guide, where the styles are in a single file. The work will continue there and this ticket can be closed.
